name: CI with Coverage and Pylint
on:
  push:
    branches:
      - main
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    # Evitar bucle infinito
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests and generate coverage report
        run: |
          coverage run -m unittest discover
          coverage xml -o cobertura.xml
          coverage report -m > coverage_report.txt
          echo "Coverage report generated:"
          tail -n 10 coverage_report.txt
      - name: Run Pylint and generate report
        run: |
          # Ejecuta pylint y guarda toda la salida en un archivo
          pylint --rcfile=.pylintrc main.py core tests > pylint_report.txt || true
          echo "Pylint report generated:"
          tail -n 10 pylint_report.txt
      - name: Generate reports file
        run: |
          cat << 'EOF' > generate_reports.py
          import os
          def read_file(filepath):
              if not os.path.exists(filepath):
                  return f"Error: Report file not found at {filepath}"
              with open(filepath, "r") as f:
                  return f.read()
          coverage_report = read_file("coverage_report.txt")
          pylint_report = read_file("pylint_report.txt")
          reports_content = f"""# Automated Reports
          ## Coverage Report
          ```text
          {coverage_report}
          ```
          ## Pylint Report
          ```text
          {pylint_report}
          ```
          """
          with open("REPORTS.md", "w") as f:
              f.write(reports_content)
          EOF
          python generate_reports.py
          echo "REPORTS.md generated successfully."
      - name: Create Pull Request for reports
        if: github.ref == 'refs/heads/main'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: Update automated reports [skip ci]"
          title: ":bar_chart: Update Automated Reports"
          body: |
            🤖 **Automated report update**
            This PR updates the following files with the latest data:
            - REPORTS.md
            - coverage_report.txt
            - pylint_report.txt
            Generated automatically by GitHub Actions.
          branch: update-reports
          delete-branch: true
          base: main
          add-paths: |
            REPORTS.md
            pylint_report.txt
            coverage_report.txt
      - name: Auto-merge Pull Request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          # Esperar un momento para que el PR esté completamente creado
          sleep 5
          # Intentar mergear automáticamente (si el bot tiene permisos)
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} \
            --squash \
            --delete-branch \
            --admin || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
